### ISSUE TITLE
Get-UAJobOutput : Only showing ERR output.

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal-legacy#102]
#### Description

Seems like Get-UAJobOutput isnt returning anything other than ERR messages. 

Expected: Returns stream output for a job. This includes error, warning, information, debug and verbose. Use Get-UAJobPipelineOutput to receive pipeline output.

Results: Only showing [ERR] messages under job output and skipping over [INF]

#### Additional Information

![image](https://user-images.githubusercontent.com/15201245/108880491-f5571a00-75c7-11eb-8ec8-780b79594341.png)

![image](https://user-images.githubusercontent.com/15201245/108880045-8083e000-75c7-11eb-8338-7bf2eaa1a9b0.png)

`New-PSUEndpoint -Url "/offboard/:account" -Method "Get" -Endpoint {
    $Server = "redacted"
    $AuthUser = Get-UAVariable -Name 'redacted'
    $AppToken = 'redacted'
	
    Connect-UAServer -ComputerName $Server -AppToken $AppToken
 
    if (Get-aduser $Account) {
        try {
			Invoke-UAScript -Script $ScriptName -Account $Account -Credential $AuthUser -AppToken $AppToken | Tee-Object -Variable job | Wait-UAJob
            $CurrentJob = Get-UAJob -Id $Job.Id 
            Write-Output "User: $($CurrentJob.Identity.Name)"  
 
            if ($CurrentJob.Status -eq 'Completed') {
                Write-Output "Job #$($CurrentJob.id) Completed."

                $Pipeline = Get-UAJobPipelineOutput -Job $CurrentJob
                Write-Output "PipelineOutput: $Pipeline"
	            $UAJobOutput = Get-UAJobOutput -Job $CurrentJob | Select-Object -Expand Message
                "UAJobOutput: $UAJobOutput"
            } 
            else {
                $Output = Get-UAJobOutput -Job $CurrentJob | Select-Object -Expand Message
                New-PSUApiResponse -StatusCode 400 -Body "Failed: $Output [ERROR: $_]"
            } 
        }
        catch {
            New-PSUApiResponse -StatusCode 400 -Body "Failed! [ERROR: $_]"
        }
    }
    else {
        New-PSUApiResponse -StatusCode 400 -Body "User: $Account not found"
    }
 
} -Authentication -Role "Administrator"`

#### Version Information

- Universal: 1.5.9
- Universal Hosting Method (IIS, Executable, docker etc): IIS
- PowerShell: Any
- Operating System: Any

**Comment by adamdriscoll** [comment]
This will be fixed in 1.5.14.

**Comment by adamdriscoll** [comment]
We've released 1.5.14. If this resolves your issue, please close this issue.

**Comment by mikedhanson** [comment]
Sorry for the late reply on this but tested it and its working as expected. Thanks again for looking into this.
