### ISSUE TITLE
How change the default Navbar color etc?

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal-legacy#103]
Hi,
I classify this as a bug! I can't find any documentation how I can change the default navigationbar color and also remove the "dark-mode" button.

**Comment by adamdriscoll** [comment]
We're adding a -DisableThemeToggle to New-UDDashboard in 1.5.14. I responded to your question about the navbar color on the forums.

**Comment by rwidmark** [comment]
> We're adding a -DisableThemeToggle to New-UDDashboard in 1.5.14. I responded to your question about the navbar color on the forums. 

Sounds perfect!

**Comment by rwidmark** [comment]
I'm closing this as you have added the hide dark/light button in the navbar now :)
