### ISSUE TITLE
Fails to read dashboards.ps1 on fresh Install

### ISSUE THREAD

**Issue by JustinGrote** [ironmansoftware/powershell-universal-legacy#11]
### Issue
When attempting to bootstrap Powershell Universal and pre-creating a dashboards.ps1 file prior to full data population, I get the following error
```
fail: UniversalAutomation.Services.UniversalConfigurationService[0]
      Failed to read configuration file. dashboards.ps1
System.Exception: Error while deserializing. Object reference not set to an instance of an object.
   at UniversalAutomation.PowerShellSerializer`1.Deserialize(String script, IDatabase database, IConfigurationService configService) in C:\src\universal\src\UniversalAutomation\Services\PowerShellSerializer.cs:line 36
   at UniversalAutomation.Services.UniversalConfigurationService.Read[T](Func`2 includes) in C:\src\universal\src\UniversalAutomation\Services\UniversalConfigurationService.cs:line 278
```

However, if I start the dashboard again afterwards, it works just fine. I assume there is some first run initialization that just hasn't completed or populated into the DB at the time that this is executed.

### Reproduce
1. Place "Hello World" test file in test.ps1
```powershell
New-UDDashboard -Title "Hello, World!" -Content {
    New-UDTypography -Text "Hello, World!"

    New-UDButton -Text "Learn more about Universal Dashboard" -OnClick {
        Invoke-UDRedirect https://docs.ironmansoftware.com
    }
}
```

1. Run bootstrap script in same folder as the test.ps1
```
& ([ScriptBlock]::Create((iwr git.io/BPU))) -wait -reset
```

1. Ctrl-C and then run again without -reset (which deletes the DB and associated files), there will be no error.

**Comment by adamdriscoll** [comment]
This will be resolved in 1.2.9. The problem was that we were deploying the dashboard assets (frameworks\components) after reading the dashboards.ps1 file so when it went to start the dashboards, there were no assets to retrieve from the DB and it resulted in this error. 

Now we just deploy the assets before and we're good to go.
