### ISSUE TITLE
Issue tracker About link not working for Bug reports / Feature request.

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/powershell-universal-legacy#117]
The link when creating an bug / feature request state : https://github.com/ironmansoftware.com
This lead to a 404. 
The template link  should instead be: https://github.com/ironmansoftware/issues 
(I figured it out eventually following another issue from the forum)

--- Current template with bad link

### About 

Note that an issue reported here is in regard to the components in this repository. If you need to open an issue for the PowerShell Universal platform, please use the [Ironman Software Issue Tracker](https://github.com/ironmansoftware.com).

#### Description

A clear and concise description of what the issue is.

#### Additional Information

Please provide additional information. This may include a forum post, some info about your environment that might be helpful or a script example to reproduce this issue. 

#### Version Information

- Universal: 1.3.0
- Universal Hosting Method (IIS, Executable, docker etc): Any
- PowerShell: Any
- Operating System: Any

**Comment by adamdriscoll** [comment]
Resolved. Thanks!
