### ISSUE TITLE
Authenticated API's report "unauthenticated" when in the "view" screen of the api

### ISSUE THREAD

**Issue by RWGHC** [ironmansoftware/powershell-universal-legacy#12]
#### Description

when editing an API endpoint of an authenticated API in the screen where you enter the code the API indicates False for Authentication.  

Authentication = False
-

#### Additional Information

Everything seems to work as expected, just not updating that field

#### Version Information

- Universal: 1.2.8
- Universal Hosting Method IIS
- PowerShell: 7
- Operating System: Windows 2019

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This has been resolved in version 1.3
