### ISSUE TITLE
Issues while updating dashboard properties

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal-legacy#14]
### Description

When importing a dashboard a filepath is specified, however when editing properties on a dashboard the filepath is not a property:
![image](https://user-images.githubusercontent.com/10046621/88276769-846d1e00-ccd7-11ea-8375-e23df79ec49a.png)
Also noticed -1 on the ps version at times.
After updating an imported dashboard will loose its filepath.
It seems this can also cause dupliated dashboards if renaming (see second gif)

Loosing filepath:
![modify_dash_properties_issue2](https://user-images.githubusercontent.com/10046621/88419251-c8961680-cddc-11ea-8552-ffa62370d5cd.gif)

Duplicate Entry:
![modify_dash_properties_issue1](https://user-images.githubusercontent.com/10046621/88419260-cc299d80-cddc-11ea-9d19-edfd8d523cf3.gif)

#### Version Information

- Universal: Latest Nightly Build
- Universal Hosting Method (IIS, Executable, docker etc): IIS
- PowerShell: 5.1
- Operating System: Win

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This should be resolved in 1.3.1 and the latest nightly builds.
