### ISSUE TITLE
new-uddashboard -footer style is not defined

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal-legacy#15]
#### Description
After migrating a UD 2.9 dashboard to universal FW 2.9.1beta6
The dashboard starts up, however there is a blank white screen.
On inspecting the developer console it shows an issue with new-udfooter style property

#### Additional Information
`$footer = New-UDFooter -Copyright "Systems Management Automation. UD: $udversion"`
`New-UDDashboard -Title "Automation Dashboard" -Theme $theme -Pages $pages -Footer $footer`

![image](https://user-images.githubusercontent.com/10046621/88342527-764eea00-cd37-11ea-866b-8006ffd4b089.png)

#### Version Information

- Universal: 1.3.0
- Universal Hosting Method (IIS, Executable, docker etc): IIS
- PowerShell: 5.1
- Operating System: Win

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This will be fixed in tonight's nightly build. Also, we won't show a white screen any more. I fixed it so the error message will be presented right in the browser. No need to look at dev tools.
