### ISSUE TITLE
Encoding not recognized for special characters like Umlaute

### ISSUE THREAD

**Issue by claudiospizzi** [ironmansoftware/powershell-universal-legacy#17]
#### Description

After changing a script in the PowerShell Universal Automation online editor, the encoding is changed from UTF8 with BOM to UTF without BOM. We save our scripts as UTF8 with BOM because we use characters like Umlaute. For example, we will send some mails with PowerShell. The mail body is hard coded into the script ps1 file. They should arrive like this:
_Freundliche Grüsse_ 

But we get the following:
_Freundliche GrÃ¼sse_ 

I guess the file is at some point not recognized as UTF8 file and because of this, the special characters like Umlaute are not handled correctly.

#### Additional Information

First we would prefer, if all scripts in the online editor are stored as UTF8 with BOM instead of UTF8. Or at least that scripts which have an encoding UTF8 with BOM, that these scripts will keep the encoding.

#### Version Information

- Universal: 1.2.8
- Universal Hosting Method: IIS
- PowerShell: 5.1
- Operating System: WS2019

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This is resolved in tonight's nightly build and will be a part of v1.3.1
