### ISSUE TITLE
Schedule Job / Script: Option to set the job to fail if running longer than X seconds/minutes.

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/powershell-universal-legacy#19]
#### Description

Not sure if this option should be set at the Script level, or at the Schedule level (Or both? Script = Default, but can be tweaked for the Schedule?).

Allow user to set a Timeout value for the Script execution if the script is stuck, or is running for too long unexpectedly.

**Comment by adamdriscoll** [comment]
This has been implemented in 1.5.
