### ISSUE TITLE
Can't Schedule Script/Job

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/powershell-universal-legacy#20]
#### Description

Unable to schedule a script, it adds it, but sets it as 'run one time'. And not able to add more than one. i have to remove the faulty one, and try adding another, but still not working.

#### Additional Information

Fresh install of 1.2.9, then upgraded to 1.2.10 before adding any scripts. this is a new environment.

#### Version Information

- Universal: 1.2.10
- Universal Hosting Method (IIS, Executable, docker etc): Windows MSI install
- PowerShell: 5.1
- Operating System: 2019 Server

**Comment by adamdriscoll** [comment]
This has been resolved in 1.3
