### ISSUE TITLE
Set-UDElement on textbox not rendering properly

### ISSUE THREAD

**Issue by eefisherv** [ironmansoftware/powershell-universal-legacy#21]
when I do that this in my code, it updates the field, but doesn’t focus it so that the label moves over the item.

$TheCostCenter = $Cache:CostCenterMap | Where-Object Office -eq $TheLocation | Select-Object CostCenter
Set-UDElement -Id ‘txtCostCenter’ -Properties @{value = $TheCostCenter.CostCenter}
Sync-UDElement -ID ‘txtCostCenter’

![image](https://user-images.githubusercontent.com/61011760/89106215-f8a17300-d3f5-11ea-8ea4-3c01732283e7.png)

When I click inside the box, it moves properly…

![image](https://user-images.githubusercontent.com/61011760/89106220-ff2fea80-d3f5-11ea-9a85-6c71673ba8da.png)

Move out… goes back to “overwrite” mode.

https://forums.universaldashboard.io/t/i-am-a-noob-trouble-setting-textbox-with-button-click/3256/2

#### Version Information

- Universal: 1.3.0
- Universal Hosting Method (IIS, Executable, docker etc): IIS
- PowerShell: 5.1.17763.1007
- Operating System: Windows Server 2019

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
Fixed in 1.4.4

**Comment by dank42** [comment]
Still an issue in 1.4.5 it seems
