### ISSUE TITLE
New-UDTypography Style Switch disabled (Moved from old issue tracker)

### ISSUE THREAD

**Issue by eefisherv** [ironmansoftware/powershell-universal-legacy#22]
#### Description
(Moved over from old issue tracker)

Style switch is not enabled in UD v1.3... looks like its commented out in the JSX.

render() {
const {
id,
// classes,
// style,
align,
gutterBottom,
noWrap,
// isParagraph,
variant,
refreshInterval,
// isEndpoint,
autoRefresh,
} = this.props
const { text } = this.state
return (

{text}
<ReactInterval
timeout={refreshInterval * 1000}
enabled={autoRefresh}
callback={this.onLoadData}
/>

Discussion:
https://forums.universaldashboard.io/t/new-udtypography-style-how-to-change-text-color/3200/2

#### Additional Information

Please provide additional information. This may include a forum post, some info about your environment that might be helpful or a script example to reproduce this issue. 

#### Version Information

- Universal: 1.3.0 (V3)
- Universal Hosting Method: IIS
- PowerShell: 5.1.17763.1007
- Operating System: Windows 2019 Server

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This is in tonight's nightly build and will be a part of v1.3.1 and UDv3.0.1
