### ISSUE TITLE
Previously scheduled jobs are still run, even after removal from Scheduled Jobs and not Visible in Schedule.ps1 file

### ISSUE THREAD

**Issue by TmJr75** [ironmansoftware/powershell-universal-legacy#26]
#### Description

At the moment I run Universal Dashboard on my laptop, and I had previously scheduled a few scripts.
I removed these, as I move the machine to and back from work, but they still run or try to run at previously scheduled times.
If the passed time has gone, it will start all failed / missed tasks when the machine starts up. 
The Scheduled jobs does not show up in Schedules, and the jobs are not visible in Schedule.ps1 file. 

#### Version Information

- Universal: 1.3.0
Windows 10 - MSI Install
- PowerShell: Any
- Operating System: Windows 10

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
@TmJr75  - Seeing this too. I'll get this fixed today. 

Restarting the service resolves it. Obviously, not a great workaround.

**Comment by adamdriscoll** [comment]
This is fixed in tonight's nightly build and will be available in 1.3.1.
