### ISSUE TITLE
New-UDUpload only works once

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal-legacy#27]
#### Description

https://forums.universaldashboard.io/t/new-udupload-only-works-once/3293

#### Additional Information

https://forums.universaldashboard.io/t/new-udupload-only-works-once/3293

#### Version Information

- Universal: 1.3.0
- Universal Hosting Method (IIS, Executable, docker etc): Any
- PowerShell: Any
- Operating System: Any

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by borough11** [comment]
further info:
Writing the uploaded file into a subfolder in the “Repository” directory (C:\ProgramData\UniversalAutomation\Repository\uploads) was causing the issue. I guess the "repository" must be a monitored location and when the new file was written, that was causing a problem. I changed the directory where I was writing the file to (to C:\testupload, just to see if this was the issue) and now the dashboard remains working after 1 upload, and subsequent uploads continue to work with the file written into C:\testupload correctly!
