### ISSUE TITLE
Write-Host with -ForegroundColor willl show extra line break in output

### ISSUE THREAD

**Issue by claudiospizzi** [ironmansoftware/powershell-universal-legacy#31]
#### Description

If we use a foreground color output with Write-Host, the output add an extra line break after the text itself.

Expected option 1: Show the colored output in the console, no new line.
Expected option 2: Just ignore the color, show as white output but no new line.

#### Additional Information

This is the used script:
![image](https://user-images.githubusercontent.com/1934246/89786611-8549e080-db1c-11ea-80b3-427cad1702f6.png)

That's the output:
![image](https://user-images.githubusercontent.com/1934246/89786590-7e22d280-db1c-11ea-8ea5-2dc91c25ce92.png)

#### Version Information

- Universal: 1.2.8
- Universal Hosting Method: IIS
- PowerShell: 5.1
- Operating System: WS2019

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
Fixed in 1.4.
