### ISSUE TITLE
User Module Path wrong for PowerShell 5.1

### ISSUE THREAD

**Issue by claudiospizzi** [ironmansoftware/powershell-universal-legacy#32]
#### Description

The $Env:PSModulePath in the automation script executed as 5.1 (aka Windows PowerShell) is using the PowerShell (Core) module path.

The user module path should point to C:\Users\%username%\Documents\WindowsPowerShell\Modules for scripts using PowerShell 5.1.

Background:
We have controller scripts auto loading the dependencies (modules) into the current user module path. The installation will put the modules into the current "WindowsPowerShell" module path, but they are not found by the module importing because the module path is wrong.

#### Additional Information

Demo script:
![image](https://user-images.githubusercontent.com/1934246/89788231-1cb03300-db1f-11ea-9953-e213fcbb3c4d.png)

Output showing the wrong module path:
![image](https://user-images.githubusercontent.com/1934246/89788324-436e6980-db1f-11ea-9ede-01430165374a.png)

#### Version Information

- Universal: 1.2.8
- Universal Hosting Method: IIS
- PowerShell: 5.1
- Operating System: WS2019

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by claudiospizzi** [comment]
Still the same with v1.3.0

**Comment by adamdriscoll** [comment]
This is resolved in the master branch and will be available in 1.4 and tonight's nightly build.
