### ISSUE TITLE
Show-UDToast -ReplaceToast not working

### ISSUE THREAD

**Issue by JustinGrote** [ironmansoftware/powershell-universal-legacy#33]
#### Description
Appears to be regression of https://github.com/ironmansoftware/universal-dashboard/issues/1449 in PowershellUniversal 1.3.0

As a workaround I do a `hide-udtoast` immediately before the `show-udtoast` for now
``` powershell
                        New-UDButton -Icon (New-UDIcon -Icon unlock) -Text 'Unlock' -OnClick { 
                            Show-UDToast -Id mytoast -Message "Unlocking $($RowItem.SamAccountName)" -Duration 5000
                            sleep 2
                            Show-UDToast -Id mytoast -Message "Unlocked!" -Duration 5000  -ReplaceToast
                        } 
```

![Capture](https://user-images.githubusercontent.com/15258962/89956894-ea6c0780-dbea-11ea-8304-c8f8adf9e795.gif)

#### Version Information

- Universal: 1.3.0
- Universal Hosting Method (IIS, Executable, docker etc): Executable
- PowerShell: 7.0.3
- Operating System: Windows
- Browser: Edge Chromium 84.0.522.52

**Comment by adamdriscoll** [comment]
Resolved in v1.3.1
