### ISSUE TITLE
Unable to add ServerCertificateValidationCallback

### ISSUE THREAD

**Issue by claudiospizzi** [ironmansoftware/powershell-universal-legacy#37]
#### Description

Using the following code throws an error in PowerShell Universal Automation using PS v5.1 but is working if it's executed in the PowerShell Console host. Also adding the assembly loading does not help.

```powershell
[System.Reflection.Assembly]::LoadWithPartialName('System.Security.Cryptography.X509Certificates') | Out-Null

Add-Type -TypeDefinition '
    using System;
    using System.Net;
    using System.Net.Security;
    using System.Security.Cryptography.X509Certificates;

    public static class GrantUnsignedSslCertificate
    {
        public static bool ReturnTrue(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            return true;
        }

        public static RemoteCertificateValidationCallback GetDelegate()
        {
            return new RemoteCertificateValidationCallback(GrantUnsignedSslCertificate.ReturnTrue);
        }
    }
';
```

This error message is thrown:

```
c:\Users\<username>\AppData\Local\Temp\xqxepz2x.0.cs(9) : The type name 'X509Chain' could not be found. This type has been forwarded to assembly 'System.Security.Cryptography.X509Certificates, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Consider adding a reference to that assembly. c:\Users\<username>\AppData\Local\Temp\xqxepz2x.0.cs(8) : { c:\Users\<username>\AppData\Local\Temp\xqxepz2x.0.cs(9) : >>> public static bool ReturnTrue(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) c:\Users\sa-pwshuniversalprod\AppData\Local\Temp\xqxepz2x.0.cs(10) : {
```

#### Additional Information

The previous code is required to use `Invoke-RestMethod`, an API not having a valid SSL certificate. The RemoteCertificateValidationCallback will always return true.

```powershell
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = [GrantUnsignedSslCertificate]::GetDelegate()
```

#### Version Information

- Universal: 1.3.0
- Universal Hosting Method: IIS
- PowerShell: 5.1
- Operating System: WS2019

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by gitbute** [comment]
I also have the same bug. It appeared while trying to use the module 'Posh-IBWAPI'

Version Information
Universal: 1.3.1
Universal Hosting Method: IIS
PowerShell: 5.1
Operating System: WS2016

**Comment by adamdriscoll** [comment]
This works in the latest master branch and current nightly builds. I tried with both PowerShell 5.1 and 7.0.3.

**Comment by gitbute** [comment]
Sadly im still unable to run above code.. currently on Universal 1.6.0 beta

@adamdriscoll 
can you confirm this behaviour?
