### ISSUE TITLE
New-UACredential Missing

### ISSUE THREAD

**Issue by i4vision** [ironmansoftware/powershell-universal-legacy#38]
I'm getting the following error when I try to use New-UACredential

The term 'New-UACredential' is not recognized as the name of a cmdlet, function, script file, or operable program.

I can use others UA commands like Get-UAScript, Get-UAVariable etc

**Comment by adamdriscoll** [comment]
New-UACredential has been replaced with New-PSUVariable in more recent versions of PSU. https://docs.powershelluniversal.com/automation/variables#creating-a-secret-variable
