### ISSUE TITLE
Out-UDTableData: The parameter 'property' is actually 'Properties'

### ISSUE THREAD

**Issue by raandree** [ironmansoftware/powershell-universal-legacy#42]
#### Description

As documented 'Out-UDTableData' should have a parameter named 'property' but it is 'Properties'. This is not according to the PowerShell naming convention.

#### Additional Information
None

#### Version Information

- Universal: 1.3.2
- Universal Hosting Method (IIS, Executable, docker etc): Any
- PowerShell: Any
- Operating System: Any

#### Internal Issue

**Comment by adamdriscoll** [comment]
This has been resolved in tonight's nightly build. We've added an alias for backwards compatiblity that will be removed on the next major version.
