### ISSUE TITLE
macOS-Support

### ISSUE THREAD

**Issue by datenschieber** [ironmansoftware/powershell-universal-legacy#43]
I would like to see support for macOS (no docker images). Currently only Windows and Linux are support. Same request applies to the VS Code extension.

Is this on your roadmap?

**Comment by adamdriscoll** [comment]
Mac support is coming to Universal 1.5 (likely next month). Mac support for PoshTools is on the roadmap but not slated for a release quite yet. I would expect it in the next couple of months.

**Comment by adamdriscoll** [comment]
I'd be curious which components are failing for you. UDv3 should be backwards compatible with existing UD components so maybe there is just something we need to fix.

**Comment by adamdriscoll** [comment]
This has been implemented in 1.5. It will be available in tonight's nightly build.
