### ISSUE TITLE
Switch parameters not supported

### ISSUE THREAD

**Issue by jantari** [ironmansoftware/powershell-universal-legacy#44]
#### Description

Parameters of type `[switch]` are very common in PowerShell scripts, and they are shown in the WebUI as a toggle-switch, but they cause an error when trying to run any script with them in v1.3.2

#### Additional Information

The error message is:

```plain
[09:22:03] [ERR] A positional parameter cannot be found that accepts argument 'False'.
```

The Param-block in my example script is:

```powershell
[CmdletBinding()]
Param (
    [int]$LastSeenDaysAgo = 90,
    [switch]$GetADStatus,
    [Parameter( Mandatory = $true )]
    [pscredential]$APICredentials
)
```

This error occurs whether the toggle switch in the GUI is on or off, the error message will just laternate between `... that accepts argument 'False'.` and `... that accepts argument 'True'.`

#### Version Information

- Universal: 1.3.2
- Universal Hosting Method (IIS, Executable, docker etc): Executable (Kestrel)
- PowerShell: 5.1 and 7.0.3
- Operating System: Windows Server 2019 (Build 10.0.17763.1457)

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This has been resolved in 1.4 and will be available in the nightly build.
