### ISSUE TITLE
Increased Token Management through the GUI

### ISSUE THREAD

**Issue by bullbaiter** [ironmansoftware/powershell-universal-legacy#47]
#### Description

More options with token management in powershell universal, in particular those used with APIs.  We'll be generating alot of them and with no mechanism to remove them from the GUI (not revoke - more of a revoke and remove from system).  Also a way to create custom tokens from within the gui.  ex. A token for User A (who is not logged into the server) assigned to Role Y that's valid for X days, etc.

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This has been implemented and will be released in 1.5.
