### ISSUE TITLE
LoadingComponent only works once

### ISSUE THREAD

**Issue by raymix** [ironmansoftware/powershell-universal-legacy#48]
#### Description

```
    New-UDButton -Text "sync" -OnClick {
        Sync-UDElement -Id "preloader"
    }

    New-UDDynamic -Id "preloader" -Content {
        Start-Sleep -Seconds 3
        New-UDTypography -Text (Get-Date).ToString()
    } -LoadingComponent {
        New-UDProgress
    }
```

#### Additional Information

Preloader should run every time UDDynamic is synced, but it only runs once. For now workaround is to create and destroy UDProgress manually

#### Version Information

- Universal: 1.3.2
- Universal Hosting Method (IIS, Executable, docker etc): Any
- PowerShell: Any
- Operating System: Any

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
Fixed in 1.4.8
