### ISSUE TITLE
UD3 - Enable left side static navigation menu like in version 2.  Hamburger menu is only choice in V3 currently.

### ISSUE THREAD

**Issue by davidacrook** [ironmansoftware/powershell-universal-legacy#5]
#### Is your Enhancement request related to a problem? Please describe
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] and would receive great value from [...]

#### Describe how this would improve your Universal Dashboard Quality of Life
Please help us understand how this would improve your usage of universal dashboard and/or what new capabilities this enhancement would provide you with.

#### Describe alternatives you've considered
A clear and concise description of any alternative solutions or Enhancements you've considered.

#### Additional context
Add any other context or screenshots about the Enhancement request here.

**Comment by adamdriscoll** [comment]
We've added -Variant Permanent in version 1.4 to the New-UDDrawer cmdlet to provide this.
