### ISSUE TITLE
Published folder - default page

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/powershell-universal-legacy#56]
#### Description

It would be nice if Published folders picked up on a default file, such as index.html if present and / or definable through the Published Folder configuration.

This
https://demo.ironmansoftware.com/docs/index.html

VS
https://demo.ironmansoftware.com/docs  

The latter feel much more comfortable and is easy to remember. All you have to think is to do a /docs if you don't have a shortcut handy.

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This has been implemented in 1.5. https://docs.ironmansoftware.com/dashboard/published-folders#default-documents
