### ISSUE TITLE
$eventData inside New-UDSwitch -OnChange is a hashtable and not a boolean

### ISSUE THREAD

**Issue by liamwh** [ironmansoftware/powershell-universal-legacy#58]
#### Description

- $eventData inside New-UDSwitch -OnChange is a hashtable and not a boolean.
- Casting 'True' or 'False' (strings) to boolean is not working inside New-UDTableColumn.

#### Additional Information

The attached file is found inside a New-UDPage -Content block and contains comments describing the issue.
[accountsSnippet.ps1.txt](https://github.com/ironmansoftware/powershell-universal/files/5371090/accountsSnippet.ps1.txt)

#### Version Information

- Universal: 1.4.3
- Universal Hosting Method (IIS, Executable, docker etc): Executable
- PowerShell: 7.0.3
- Operating System: Windows 10

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
Fixed in 1.5.
