### ISSUE TITLE
Scheduled job "spawns" a new job after half an hour running aproximately.

### ISSUE THREAD

**Issue by TmJr75** [ironmansoftware/powershell-universal-legacy#6]
#### Description

I have created a schedule to run a script on my customers environment to check for alerts.
This is set to run every 4th hour. 
It is also the only job scheduled now, in my schedule.ps1 file:
New-PSUSchedule -Cron "0 */4 * * *" -Script "Script.ps1" -TimeZone "Europe/Oslo"

What I see happening is that it spawns the same job running again half an hour later.
(Its a job that goes through a lot of different customers).

178 | Running | Script.ps1 | 7/10/2020, 8:30 AM | NA | Admin | ViewCancel
177 | Running | Script.ps1 | 7/10/2020, 8:00 AM | NA | Admin | ViewCancel
176 | Success | Script.ps1 | 7/10/2020, 5:00 AM | 7/10/2020, 5:58 AM | Admin | View
175 | Success | Script.ps1 | 7/10/2020, 4:30 AM | 7/10/2020, 5:30 AM | Admin | View
174 | Success | Script.ps1 | 7/10/2020, 4:00 AM | 7/10/2020, 5:00 AM | Admin | View
 
It exports all information to an excel spreadsheet and when it spawns two jobs, it creates two different spreadsheets (file name is generated with date information)

#### Additional Information

Please provide additional information. This may include a forum post, some info about your environment that might be helpful or a script example to reproduce this issue. 

#### Version Information

- Universal: 1.2.8
- Universal Hosting Method (IIS)
- PowerShell: PSVersion 5.1.18362.752
- Operating System: Windows 10 - Version 1909 - Build: 18363.900

#### Internal Issue

https://github.com/ironmansoftware/universal/issues/216

**Comment by TmJr75** [comment]
Same happens if I just runs the script, so this is not related to the scheduling I think.

**Comment by adamdriscoll** [comment]
This will be resolved in 1.2.9. The issue was that our job scheduling library was assuming the job timed out after 30 minutes so it would attempt to start another job in it's place. We've extended this to 24 hours so you shouldn't run into this problem any more.
