### ISSUE TITLE
VSCode Extension: Integrated Console commands Lock up in runspace debug mode

### ISSUE THREAD

**Issue by JustinGrote** [ironmansoftware/powershell-universal-legacy#60]
#### Description

This may need to be cross-posted to Powershell Editor Services repo.

When debugging a dashboard, entering the runspace works fine and watch variables work fine, but trying to enter anything arbitrary into the integrated console locks up the session.

![Capture](https://user-images.githubusercontent.com/15258962/95901900-df4b6a00-0d48-11eb-97b1-a85f74be6c8c.gif)

#### Version Information

- Universal: 1.3.0
- Universal Hosting Method (IIS, Executable, docker etc): Any
- PowerShell: Any
- Operating System: Any

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by JustinGrote** [comment]
Appears to be Powershell Extension Related, opened tracking issue there: https://github.com/PowerShell/vscode-powershell/issues/3008

**Comment by adamdriscoll** [comment]
oh, whoops. I also opened an issue here: https://github.com/PowerShell/PowerShellEditorServices/issues/1369 

Thanks!

**Comment by adamdriscoll** [comment]
I'm going to close this issue since it's actually a problem with the extension. I'm able to do the same thing in a PowerShell console without issue.
