### ISSUE TITLE
New dashboards / API endpoint authentication are set to public by default when authentication is in use.

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/powershell-universal-legacy#64]
#### Description

Security wise, I would expect new endpoint to be created with "requiring authentication" rather than public.
Forgetting to click that button could have dire consequences as you would end up with a public endpoint.

On the other end, forgetting to set your endpoint public won't have any consequences other than the users not being able to access the endpoint until the admin. go back and enable authentication.

![image](https://user-images.githubusercontent.com/1980296/96391884-4d988e00-1188-11eb-98f8-5639a791d597.png)

This apply to both the dashboard creation and endpoint creations for any PSU instance using authentication.

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This has been resolved in a recent version.
