### ISSUE TITLE
Windows Auth with Universal Dashboard

### ISSUE THREAD

**Issue by this-is-mihai** [ironmansoftware/powershell-universal-legacy#67]
#### Description
Cannot get $User variable in Universal Dashboard

#### Additional Information

Ok, so i’m runing the latest UA 1.5.0 night build. I’ve setup UA to run as a service under a service account. Did the setspn thing accordingly to the doc here: https://docs.ironmansoftware.com/config/security#windows-authentication-outside-of-iis
Created a new Dashboard via UA. Thing is: I can single sign on from the host, even from other computers on the lan, but i can’t sign on in the dashboard. I tried display the $User variable in the dashboard. I does not show. If I select authentication on the dashboard (via UA) the I can, again single sign on on UA (no problem here) but when i go to the Universal Dashboard i just created, it pops up the Login page. In the login page i cannot sign in with any user.
Made modification to web.config : forwardWindowsAuthToken=“true”
Made modification to app setting:

```
“Authentication” : {
“Windows”: {
“Enabled”: “true”
},
```
also in app setting i modified this:

```
 “Kestrel”: {
 “Endpoints”: {
 “HTTP”: {
 “Url”: “http://*:80”
 }
}
```

#### Version Information

- Universal: 1.5.0 (latest nightbuild 26 oct)
- Universal Hosting Method (IIS, Executable, docker etc): Running as a service
- PowerShell: 5.1
- Operating System: Windows Server 2016

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
@this-is-mihai - This has been resolved in the latest 1.5.0 branch.
