### ISSUE TITLE
EventData Properties not properly populated when using -LoadFrom

### ISSUE THREAD

**Issue by JustinGrote** [ironmansoftware/powershell-universal-legacy#75]
#### Description
When doing a -LoadFrom for server side processing, the `$EventData` does not display the properties correctly.
![image](https://user-images.githubusercontent.com/15258962/97642716-18e7ca80-1a03-11eb-9346-fd5b98971fe5.png)

#### Workaround
`$Body` is still correct, so either of these will work:
`($Body | ConvertFrom-Json).properties`
`$EventData.properties = ($Body | ConvertFrom-Json).properties`

#### Additional Information

Please provide additional information. This may include a forum post, some info about your environment that might be helpful or a script example to reproduce this issue. 

#### Version Information

- Universal: 1.4.6
- Universal Hosting Method (IIS, Executable, docker etc): Any
- PowerShell: Any
- Operating System: Any

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
Fixed in 1.4.7
