### ISSUE TITLE
Powershell not-running message should redirect to dashboard if running again.

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/powershell-universal-legacy#87]
#### Description

Whenever the dashboard is not running, whether because the file is being updated and / or it was stopped, you get redirected to a not-running page. 

Eg:  https://testarea.something.com:5000/home/not-running

Even after the dashboard is found running again, the user stay stuck on the not-running url.
It would be nice if we got back to the dashboard page when refreshing instead of having to manually go in the address bar and remove the "not-running" part.

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This does this in 1.5.9. I'm not 100% what version this was added but it will now redirect to the dashboard once it starts up.

**Comment by Windos** [comment]
Yes, that's even better!
