### ISSUE TITLE
Get-PSUDashboard Support for different ports

### ISSUE THREAD

**Issue by qlikq** [ironmansoftware/powershell-universal-legacy#89]
#### Description

Would it be possible to add support with a new parameter for example like 'port' or start accepting different port inside Get-PSUDashboard ?
When doing :
Get-PSUDashboard -ComputerName 192.168.1.243:32777  
it creates an error that the uri is incorrect. When i skip the port, it by default goes to 5000 , and in my case port 5000 is used for some internal services on the server. I am running a docker edition 1.5.7 from official image. 
PS 7.1 , windows 10 x64, Universal 1.5.7 
I am starting to learn Universal, and not sure about other cmdlets, would they also be locked to just port 5000 ?

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
If you include http, you should be able to use a different port: `Get-PSUDashboard -ComputerName http://192.168.1.243:32777`

**Comment by qlikq** [comment]
> If you include http, you should be able to use a different port: `Get-PSUDashboard -ComputerName http://192.168.1.243:32777`

Thank you Adam, it worked as you have explained.
