### ISSUE TITLE
MSI Upgrade overwrites appsettings.json

### ISSUE THREAD

**Issue by molson98** [ironmansoftware/powershell-universal-legacy#96]
#### Description

When upgrading PowerShell Universal it overwrites the appsettings.json file. This then requires going back in and making all the changes over again.

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
Hi @molson98 - Did the one in %ProgramData% get overwritten or the one in program files? 

You can create one in %ProgramData% that shouldn't be overwritten during upgrades: https://docs.ironmansoftware.com/get-started/getting-started/upgrading#appsettings-json

**Comment by molson98** [comment]
I completely missed that in the docs. Thank you!
