### ISSUE TITLE
New-UDDYnamic -$ArgumentList[0] not working

### ISSUE THREAD

**Issue by wsl2001** [ironmansoftware/powershell-universal-legacy#97]
#### Description

When using -$ArgumentList[0] with New-UDDynamic its null.

#### Additional Information

An error occurred: Cannot index into a null array.

Endpoint: 16698f03-6cad-4aa1-9abe-85267c414728

Session: ce154625-10d0-461b-819e-50f12975e16e

File: 

Endpoint Start Line: 3

Endpoint End Line: 5

Stack Trace: at <ScriptBlock>, <No file>: line 3
example tested

New-UDPage -Name "test" -Content { 

$Var = 123 
New-UDDynamic -Content {
   new-UDTypography -Text $ArgumentList[0]
} -ArgumentList $Var

}

#### Version Information

- Universal: 1.5.10
- Universal Hosting Method (IIS, Executable, docker etc):  IIS
- PowerShell: 7.1
- Operating System: Windows 2019 standard 

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This is fixed in 1.5.11.
